import {
	GOLDEN_REFERENCE_HUMANOID_ASSET,
	GOLDEN_REFERENCE_IDLE_BAKED_ASSET,
	GOLDEN_REFERENCE_WALK_BAKED_ASSET,
	PROCEDURAL_MANNEQUIN_HAIR_V0_ASSET,
	PROCEDURAL_MANNEQUIN_V0_ASSET,
} from "@adventure-game-builder/three-asset-preview";

export type {
	ThreeCharacterAnimationMapping,
	ThreeCharacterAnimationState,
	ThreeVisualAssetCategory,
	ThreeVisualAssetDefinition,
} from "@adventure-game-builder/three-asset-preview";

import type { ThreeVisualAssetDefinition } from "@adventure-game-builder/three-asset-preview";
import { characterAssetProblem } from "../../data/characterAssets";
import type { CharacterGameAsset } from "../../types/game";

// Built-in/demo registry only. These assets live under public/ so Vite serves
// them from the same stable URLs in dev and production builds.
export const THREE_VISUAL_ASSET_REGISTRY: ThreeVisualAssetDefinition[] = [
	{
		hiddenFromBrowser: true,
		category: "object",
		defaultHeightOffset: 0.45,
		defaultScale: 0.45,
		tags: ["demo", "primitive"],
		id: "demo-box",
		kind: "glb",
		name: "Demo Box",
		url: "/assets/demo/Box.glb",
	},
	{
		hiddenFromBrowser: true,
		category: "object",
		castShadow: true,
		defaultScale: 0.22,
		id: "pirate-chest",
		kind: "glb",
		name: "Pirate Chest",
		receiveShadow: true,
		tags: ["container", "treasure"],
		url: "/assets/pirate-demo/chest.glb",
	},
	{
		hiddenFromBrowser: true,
		category: "object",
		defaultScale: 0.45,
		id: "pirate-barrel",
		kind: "glb",
		name: "Pirate Barrel",
		receiveShadow: true,
		tags: ["prop", "storage"],
		url: "/assets/pirate-demo/barrel.glb",
	},
	{
		hiddenFromBrowser: true,
		category: "object",
		defaultScale: 0.45,
		id: "pirate-crate",
		kind: "glb",
		name: "Pirate Crate",
		receiveShadow: true,
		tags: ["prop", "storage"],
		url: "/assets/pirate-demo/crate.glb",
	},
	{
		hiddenFromBrowser: true,
		category: "environment",
		castShadow: true,
		defaultScale: 0.24,
		id: "pirate-palm",
		kind: "glb",
		name: "Pirate Palm",
		receiveShadow: true,
		tags: ["foliage", "land"],
		url: "/assets/pirate-demo/palm-straight.glb",
	},
	{
		hiddenFromBrowser: true,
		category: "environment",
		castShadow: true,
		defaultScale: 0.35,
		id: "pirate-rocks",
		kind: "glb",
		name: "Pirate Rocks",
		receiveShadow: true,
		tags: ["environment", "land", "shore"],
		url: "/assets/pirate-demo/rocks-a.glb",
	},
	{
		hiddenFromBrowser: true,
		category: "vehicle",
		castShadow: true,
		defaultScale: 0.12,
		id: "pirate-small-ship",
		kind: "glb",
		name: "Pirate Small Ship",
		receiveShadow: true,
		tags: ["boat", "pirate", "water"],
		url: "/assets/pirate-demo/ship-pirate-small.glb",
	},
	{
		hiddenFromBrowser: true,
		category: "object",
		defaultScale: 0.4,
		id: "pirate-dock",
		kind: "glb",
		name: "Pirate Dock",
		receiveShadow: true,
		tags: ["platform", "waterfront"],
		url: "/assets/pirate-demo/structure-platform-dock.glb",
	},
	{
		hiddenFromBrowser: true,
		category: "object",
		defaultScale: 0.45,
		id: "pirate-flag",
		kind: "glb",
		name: "Pirate Flag",
		receiveShadow: true,
		tags: ["decoration", "flag"],
		url: "/assets/pirate-demo/flag-pirate.glb",
	},
	{ ...GOLDEN_REFERENCE_HUMANOID_ASSET, hiddenFromBrowser: true },
	{ ...GOLDEN_REFERENCE_IDLE_BAKED_ASSET, hiddenFromBrowser: true },
	{ ...GOLDEN_REFERENCE_WALK_BAKED_ASSET, hiddenFromBrowser: true },
	{ ...PROCEDURAL_MANNEQUIN_V0_ASSET, hiddenFromBrowser: true },
	{ ...PROCEDURAL_MANNEQUIN_HAIR_V0_ASSET, hiddenFromBrowser: true },
	{
		hiddenFromBrowser: true,
		category: "character",
		animations: {
			attack: {
				assetId: "pirate-character-attack",
				clipName: "Armature|Attack|baselayer",
			},
			defeated: {
				assetId: "pirate-character-dead",
				clipName: "Armature|Dead|baselayer",
			},
			walk: {
				assetId: "pirate-character-walk",
				clipName: "Armature|walking_man|baselayer",
			},
		},
		defaultHeightOffset: 0,
		// Patchbeard's visible forward is native +Z; Three grid north is -Z.
		defaultRotationOffset: 180,
		defaultScale: 0.75,
		id: "pirate-character-base",
		kind: "glb",
		materialProfile: "standard",
		name: "Captain Patchbeard (Base)",
		receiveShadow: false,
		tags: ["base", "character", "pirate", "skinned"],
		url: "/assets/pirate-character/Meshy_AI_Captain_Patchbeard_biped_Character_output.glb",
	},
	{
		hiddenFromBrowser: true,
		category: "character",
		animations: {
			attack: {
				assetId: "pirate-character-attack",
				clipName: "Armature|Attack|baselayer",
			},
			defeated: {
				assetId: "pirate-character-dead",
				clipName: "Armature|Dead|baselayer",
			},
			walk: {
				assetId: "pirate-character-walk",
				clipName: "Armature|walking_man|baselayer",
			},
		},
		defaultHeightOffset: 0,
		// Patchbeard's visible forward is native +Z; Three grid north is -Z.
		defaultRotationOffset: 180,
		defaultScale: 0.75,
		id: "pirate-character-walk",
		kind: "glb",
		materialProfile: "standard",
		name: "Captain Patchbeard (Walk)",
		receiveShadow: false,
		tags: ["animation", "character", "pirate", "skinned", "walk"],
		url: "/assets/pirate-character/Meshy_AI_Captain_Patchbeard_biped_Animation_Walking_withSkin.glb",
	},
	{
		animationOnly: true,
		hiddenFromBrowser: true,
		category: "character",
		id: "pirate-character-attack",
		kind: "glb",
		materialProfile: "standard",
		name: "Captain Patchbeard Attack (Animation Source)",
		receiveShadow: false,
		tags: ["animation", "attack", "character", "pirate", "skinned"],
		url: "/assets/pirate-character/Meshy_AI_Captain_Patchbeard_biped_Animation_Attack_withSkin.glb",
	},
	{
		animationOnly: true,
		hiddenFromBrowser: true,
		category: "character",
		id: "pirate-character-dead",
		kind: "glb",
		materialProfile: "standard",
		name: "Captain Patchbeard Dead (Animation Source)",
		receiveShadow: false,
		tags: ["animation", "character", "dead", "pirate", "skinned"],
		url: "/assets/pirate-character/Meshy_AI_Captain_Patchbeard_biped_Animation_Dead_withSkin.glb",
	},
	// Harbour v1: metre-space content; legacy identities above remain loadable.
	{
		id: "world-barrel",
		name: "Wooden Barrel",
		kind: "glb",
		url: "/assets/world-kit/barrel.glb",
		category: "object",
		browserCategory: "Props",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/barrel.png",
		tags: ["barrel", "wood", "container", "pirate", "harbour", "world-kit"],
	},
	{
		id: "world-crate",
		name: "Supply Crate",
		kind: "glb",
		url: "/assets/world-kit/crate.glb",
		category: "object",
		browserCategory: "Props",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/crate.png",
		tags: ["crate", "wood", "cargo", "storage", "harbour", "world-kit"],
	},
	{
		id: "world-chest",
		name: "Treasure Chest",
		kind: "glb",
		url: "/assets/world-kit/chest.glb",
		category: "object",
		browserCategory: "Props",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/chest.png",
		tags: ["chest", "treasure", "container", "iron", "harbour", "world-kit"],
	},
	{
		id: "world-dock",
		name: "Dock Section",
		kind: "glb",
		url: "/assets/world-kit/dock.glb",
		category: "object",
		browserCategory: "Buildings",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/dock.png",
		tags: ["dock", "pier", "wood", "platform", "harbour", "world-kit"],
	},
	{
		id: "world-floor",
		name: "Wooden Floor",
		kind: "glb",
		url: "/assets/world-kit/floor.glb",
		category: "object",
		browserCategory: "Buildings",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/floor.png",
		tags: ["floor", "platform", "wood", "deck", "harbour", "world-kit"],
	},
	{
		id: "world-palm",
		name: "Coastal Palm",
		kind: "glb",
		url: "/assets/world-kit/palm.glb",
		category: "environment",
		browserCategory: "Nature",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/palm.png",
		tags: ["palm", "tree", "tropical", "foliage", "harbour", "world-kit"],
	},
	{
		id: "world-bush",
		name: "Coastal Bush",
		kind: "glb",
		url: "/assets/world-kit/bush.glb",
		category: "environment",
		browserCategory: "Nature",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/bush.png",
		tags: ["bush", "plant", "foliage", "harbour", "world-kit"],
	},
	{
		id: "world-grass",
		name: "Grass Clump",
		kind: "glb",
		url: "/assets/world-kit/grass.glb",
		category: "environment",
		browserCategory: "Nature",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/grass.png",
		tags: ["grass", "plant", "foliage", "harbour", "world-kit"],
	},
	{
		id: "world-rowboat",
		name: "Rowboat",
		kind: "glb",
		url: "/assets/world-kit/rowboat.glb",
		category: "object",
		browserCategory: "Props",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/rowboat.png",
		tags: ["boat", "harbour", "wood", "shore", "harbour", "world-kit"],
	},
	{
		id: "world-railing",
		name: "Wooden Railing",
		kind: "glb",
		url: "/assets/world-kit/railing.glb",
		category: "object",
		browserCategory: "Buildings",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/railing.png",
		tags: ["fence", "rail", "wood", "dock", "harbour", "world-kit"],
	},
	{
		id: "world-wall",
		name: "Timber Wall",
		kind: "glb",
		url: "/assets/world-kit/wall.glb",
		category: "object",
		browserCategory: "Buildings",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/wall.png",
		tags: ["wall", "wood", "modular", "structure", "harbour", "world-kit"],
	},
	{
		id: "world-post",
		name: "Timber Post",
		kind: "glb",
		url: "/assets/world-kit/post.glb",
		category: "object",
		browserCategory: "Buildings",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/post.png",
		tags: ["post", "pillar", "wood", "support", "harbour", "world-kit"],
	},
	{
		id: "world-stairs",
		name: "Wooden Steps",
		kind: "glb",
		url: "/assets/world-kit/stairs.glb",
		category: "object",
		browserCategory: "Buildings",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/stairs.png",
		tags: ["stairs", "steps", "wood", "dock", "harbour", "world-kit"],
	},
	{
		id: "world-table",
		name: "Tavern Table",
		kind: "glb",
		url: "/assets/world-kit/table.glb",
		category: "object",
		browserCategory: "Props",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/table.png",
		tags: ["table", "furniture", "wood", "tavern", "harbour", "world-kit"],
	},
	{
		id: "world-stool",
		name: "Wooden Stool",
		kind: "glb",
		url: "/assets/world-kit/stool.glb",
		category: "object",
		browserCategory: "Props",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/stool.png",
		tags: ["stool", "chair", "furniture", "wood", "harbour", "world-kit"],
	},
	{
		id: "world-sack",
		name: "Grain Sack",
		kind: "glb",
		url: "/assets/world-kit/sack.glb",
		category: "object",
		browserCategory: "Props",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/sack.png",
		tags: ["sack", "fabric", "cargo", "supplies", "harbour", "world-kit"],
	},
	{
		id: "world-lantern",
		name: "Harbour Lantern",
		kind: "glb",
		url: "/assets/world-kit/lantern.glb",
		category: "object",
		browserCategory: "Props",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/lantern.png",
		tags: ["lantern", "lamp", "iron", "decoration", "harbour", "world-kit"],
	},
	{
		id: "world-sign",
		name: "Harbour Signpost",
		kind: "glb",
		url: "/assets/world-kit/sign.glb",
		category: "object",
		browserCategory: "Props",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/sign.png",
		tags: ["sign", "post", "wood", "wayfinding", "harbour", "world-kit"],
	},
	{
		id: "world-rope",
		name: "Rope Coil",
		kind: "glb",
		url: "/assets/world-kit/rope.glb",
		category: "object",
		browserCategory: "Props",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/rope.png",
		tags: ["rope", "dock", "nautical", "cargo", "harbour", "world-kit"],
	},
	{
		id: "world-rock-small",
		name: "Small Rock",
		kind: "glb",
		url: "/assets/world-kit/rock-small.glb",
		category: "environment",
		browserCategory: "Nature",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/rock-small.png",
		tags: ["rock", "stone", "shore", "harbour", "world-kit"],
	},
	{
		id: "world-rock-large",
		name: "Large Rock",
		kind: "glb",
		url: "/assets/world-kit/rock-large.glb",
		category: "environment",
		browserCategory: "Nature",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/rock-large.png",
		tags: ["rock", "stone", "shore", "harbour", "world-kit"],
	},
	{
		id: "world-shack",
		name: "Small Shack",
		kind: "glb",
		url: "/assets/world-kit/shack.glb",
		category: "object",
		browserCategory: "Buildings",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/shack.png",
		tags: ["shack", "hut", "building", "wood", "harbour", "world-kit"],
	},
	{
		id: "world-stall",
		name: "Market Stall",
		kind: "glb",
		url: "/assets/world-kit/stall.glb",
		category: "object",
		browserCategory: "Buildings",
		defaultScale: 1,
		castShadow: true,
		receiveShadow: true,
		thumbnailUrl: "/assets/world-kit/thumbnails/stall.png",
		tags: [
			"market",
			"stall",
			"shelter",
			"canvas",
			"shop",
			"harbour",
			"world-kit",
		],
	},
];

let activeRegistry = THREE_VISUAL_ASSET_REGISTRY;

function getAssetMap(): Map<string, ThreeVisualAssetDefinition> {
	return new Map(activeRegistry.map((asset) => [asset.id, asset]));
}

export function listThreeVisualAssets(
	projectAssets: CharacterGameAsset[] = [],
): ThreeVisualAssetDefinition[] {
	return [
		...activeRegistry,
		...projectAssets.flatMap((asset) => {
			if (characterAssetProblem(asset)) return [];
			return [
				{
					...PROCEDURAL_MANNEQUIN_V0_ASSET,
					id: asset.id,
					name: asset.name,
					url: asset.glbUrl,
					tags: ["character", "finalised", asset.geometryFamily],
				},
			];
		}),
	];
}

export function getThreeVisualAssetDefinition(
	assetId: string | undefined,
	projectAssets: CharacterGameAsset[] = [],
): ThreeVisualAssetDefinition | undefined {
	return assetId
		? (getAssetMap().get(assetId) ??
				listThreeVisualAssets(projectAssets).find(
					(asset) => asset.id === assetId,
				))
		: undefined;
}

export function setThreeVisualAssetRegistryForTests(
	assets: ThreeVisualAssetDefinition[],
): () => void {
	const previous = activeRegistry;
	activeRegistry = assets;
	return () => {
		activeRegistry = previous;
	};
}
